# -*- coding: utf-8 -*-
"""ExamPeriodHabitAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWXFrXximuB2zdcvvdeBPkscqoPQ5QKj
"""

import numpy as np
import matplotlib.pyplot as plt
import calendar

raw = np.genfromtxt(
    '/data/November_2025.csv',
    delimiter=',',
    dtype=str,
    skip_header=1
)

raw[raw == ""] = "nan"

dates_str = raw[:,0]
days = np.array([int(d.split('-')[-1]) for d in dates_str])

sleep      = raw[:,1].astype(float)
course     = raw[:,2].astype(float)
curriculum = raw[:,3].astype(float)
leisure    = raw[:,4].astype(float)

# FEATURE ENGINEERING

productive = course + curriculum
focus_ratio = productive / (productive + leisure + 1e-6)
balance = sleep + productive - leisure

# Exam days
exam_days = np.array([14, 15, 17, 19, 29])
is_exam = np.isin(days, exam_days)

# 3. BASIC DESCRIPTIVE STATISTICS

def describe(name, arr):
    print(f"{name}")
    print(" Mean   :", round(np.nanmean(arr),2))
    print(" Median :", round(np.nanmedian(arr),2))
    print(" Std    :", round(np.nanstd(arr),2))
    print(" Min    :", np.nanmin(arr))
    print(" Max    :", np.nanmax(arr))
    print()

print("===== DESCRIPTIVE STATISTICS =====\n")
describe("Sleep", sleep)
describe("Course Study", course)
describe("Curriculum Study", curriculum)
describe("Leisure", leisure)
describe("Total Productive", productive)

# 4. EXAM VS NON-EXAM DAY COMPARISON
# --------------------------------------------

print("===== EXAM VS NON-EXAM DAYS =====\n")

def compare(arr, label):
    print(label)
    print(" Exam days     :", round(np.nanmean(arr[is_exam]),2))
    print(" Non-exam days :", round(np.nanmean(arr[~is_exam]),2))
    print()

compare(sleep, "Sleep")
compare(curriculum, "Curriculum Study")
compare(course, "Course Study")
compare(leisure, "Leisure")
compare(productive, "Total Productive")

# 5. CORRELATION MATRIX

print("===== CORRELATION MATRIX =====\n")

data = np.vstack([sleep, course, curriculum, leisure])
labels = ["Sleep", "Course", "Curriculum", "Leisure"]
corr = np.corrcoef(data)

print("        Sleep  Course  Curric  Leisure")
for i, label in enumerate(labels):
    row = " ".join(f"{corr[i,j]:7.2f}" for j in range(len(labels)))
    print(label.ljust(10), row)

# 6. CALENDAR-BASED WEEKLY ANALYSIS

print("\n===== WEEKLY TRENDS (Calendar-Based) =====\n")

cal = calendar.monthcalendar(2025, 11)

for i, week in enumerate(cal):
    valid_days = [d for d in week if d != 0]
    idx = np.where(np.isin(days, valid_days))[0]
    if len(idx) == 0:
        continue

    print(f"Week {i+1} | Days: {valid_days}")
    print(" Sleep     :", round(np.nanmean(sleep[idx]),2))
    print(" Curriculum:", round(np.nanmean(curriculum[idx]),2))
    print(" Course    :", round(np.nanmean(course[idx]),2))
    print(" Leisure   :", round(np.nanmean(leisure[idx]),2))
    print()

# 7. BEST / WORST DAYS

print("===== BEST & WORST DAYS =====\n")

best_focus = np.argmax(focus_ratio)
worst_focus = np.argmin(focus_ratio)

print("Most focused day :", dates_str[best_focus], round(focus_ratio[best_focus],2))
print("Least focused day:", dates_str[worst_focus], round(focus_ratio[worst_focus],2))

# 8. VISUALIZATIONS

# Sleep trend
plt.figure(figsize=(12,4))
plt.plot(days, sleep, marker='o')
plt.title("Sleep Trend – November 2025")
plt.xlabel("Day")
plt.ylabel("Hours")
plt.grid(True)
plt.show()

# Study trends
plt.figure(figsize=(12,4))
plt.plot(days, curriculum, label="Curriculum (Exam Prep)", marker='o')
plt.plot(days, course, label="Course (Long-term)", marker='o')
plt.title("Study Trends")
plt.xlabel("Day")
plt.ylabel("Hours")
plt.legend()
plt.grid(True)
plt.show()

# Leisure trend
plt.figure(figsize=(12,4))
plt.plot(days, leisure, marker='o')
plt.title("Leisure Time Trend")
plt.xlabel("Day")
plt.ylabel("Hours")
plt.grid(True)
plt.show()

# Focus ratio
plt.figure(figsize=(12,4))
plt.plot(days, focus_ratio, marker='o')
plt.title("Focus Ratio Over Time")
plt.xlabel("Day")
plt.ylabel("Focus Ratio")
plt.grid(True)
plt.show()

# Balance score
plt.figure(figsize=(12,4))
plt.plot(days, balance, marker='o')
plt.title("Daily Balance Score")
plt.xlabel("Day")
plt.ylabel("Balance Score")
plt.grid(True)
plt.show()

# Total Productive Study Hours
plt.figure(figsize=(14,5))

plt.bar(days, curriculum, label='Curriculum Study (Exam Prep)')
plt.bar(days, course, bottom=curriculum, label='Course Study (Online)')

plt.title("Daily Productive Study Hours (Stacked)")
plt.xlabel("Day of November 2025")
plt.ylabel("Hours")
plt.legend()
plt.grid(axis='y')

plt.show()